#spring:
#  datasource:
#    url: 'jdbc:postgresql://localhost:5432/'
#    username: 'postgres'
#    password: 'mysecretpassword'
#    driver-class-name: 'org.postgresql.Driver'
#   jpa:
#     open-in-view: false
# logging:
#   level:
#     org:
#       springframework:
#         security: DEBUG